url: "https://axel.mx"
baseurl: "/"
title: "Axel Valdez"

permalink: /:year/:month/:title/

theme: amx

sass:
  style: compressed
  sourcemap: never

plugins:
  - jekyll-postfiles
  
months:
    - Enero
    - Febrero
    - Marzo
    - Abril
    - Mayo
    - Junio
    - Julio
    - Agosto
    - Septiembre
    - Octubre
    - Noviembre
    - Diciembre